### PR TITLE
Handlebars is up and running

### PR DESCRIPTION
**Pull request by MagicianJoshua**
Got the page up and running, header should be displayed when server is run,  nothing is functional yet.

### CODE REVIEW

**Review by Sabinkthapa — APPROVED** [review]
Keep going

**Comment by Valleyleaf** [comment]
Was this built of my prior commit or completely separate? Want to try and avoid merge issues 💥

**Review by Valleyleaf — COMMENTED** [review]
Excellent work!

**Review by Valleyleaf — APPROVED** [review]
Learning GitHub on the phone. Approved!

**Pull request merged**
